// Generated by textagent. Yours to edit: notes and reminders for the person who owns this agent.
import { DatabaseSync } from 'node:sqlite';
import type { Agent, MessageContext } from '@textagent/core';
import type { Tool } from './claude.ts';
import { formatTime, parseTime } from './time.ts';

export const MAX_NOTE_LENGTH = 2000;
export const MAX_REMINDER_LENGTH = 500;

export interface Note {
  id: number;
  text: string;
  /** Epoch ms. */
  createdAt: number;
}

/** Notes in SQLite, each belonging to one sender on one channel. */
export class Notes {
  readonly #db: DatabaseSync;

  constructor(path = 'assistant.sqlite') {
    this.#db = new DatabaseSync(path);
    this.#db.exec(`CREATE TABLE IF NOT EXISTS notes (
      id INTEGER PRIMARY KEY,
      person TEXT NOT NULL,
      text TEXT NOT NULL,
      created_at INTEGER NOT NULL
    )`);
  }

  add(person: string, text: string, now = Date.now()): Note {
    const trimmed = text.trim();
    if (!trimmed) throw new Error('The note is empty');
    if (trimmed.length > MAX_NOTE_LENGTH) throw new Error(`Notes are at most ${MAX_NOTE_LENGTH} characters`);
    const { lastInsertRowid } = this.#db
      .prepare('INSERT INTO notes (person, text, created_at) VALUES (?, ?, ?)')
      .run(person, trimmed, now);
    return { id: Number(lastInsertRowid), text: trimmed, createdAt: now };
  }

  /** This person's notes containing every word of `query` (any case), newest first; all of them for "". */
  search(person: string, query: string, limit = 20): Note[] {
    const words = query.split(/\s+/).filter(Boolean).slice(0, 10);
    const like = words.map(() => " AND text LIKE ? ESCAPE '\\'").join('');
    const patterns = words.map((w) => `%${w.replace(/[\\%_]/g, (c) => `\\${c}`)}%`);
    return this.#db
      .prepare(`SELECT id, text, created_at AS createdAt FROM notes WHERE person = ?${like} ORDER BY id DESC LIMIT ?`)
      .all(person, ...patterns, limit) as unknown as Note[]; // the row shape of the table above
  }

  /** False if this person has no note with that id. */
  delete(person: string, id: number): boolean {
    return this.#db.prepare('DELETE FROM notes WHERE person = ? AND id = ?').run(person, id).changes > 0;
  }

  close(): void {
    this.#db.close();
  }
}

/**
 * The assistant's tools for one conversation. Notes belong to the person texting, and reminders go back to
 * this conversation: both are fixed here from the message, so nothing Claude writes can read someone else's
 * notes or send a reminder anywhere else.
 */
export function assistantTools(
  agent: Pick<Agent, 'schedule' | 'listScheduled' | 'cancelScheduled'>,
  ctx: MessageContext,
  notes: Notes,
  timezone: string,
): Tool[] {
  const person = `${ctx.channel.name}:${ctx.sender.id}`;
  const show = (note: Note) => `#${note.id} (${formatTime(note.createdAt, timezone).slice(4, 14)}): ${note.text}`;
  const pending = () => agent.listScheduled({ thread: ctx.thread, status: 'pending' });

  return [
    {
      name: 'save_note',
      description: 'Saves a note for the owner to find later.',
      input_schema: {
        type: 'object',
        properties: { text: { type: 'string', description: 'The note, in their words.' } },
        required: ['text'],
        additionalProperties: false,
      },
      run(input) {
        return `Saved as #${notes.add(person, String(input.text)).id}.`;
      },
    },
    {
      name: 'search_notes',
      description:
        'Finds saved notes that contain every word of the query, newest first. An empty query lists the newest.',
      input_schema: {
        type: 'object',
        properties: { query: { type: 'string', description: 'A few words the note would contain.' } },
        required: ['query'],
        additionalProperties: false,
      },
      run(input) {
        const found = notes.search(person, String(input.query));
        return found.length ? found.map(show).join('\n') : 'No matching notes.';
      },
    },
    {
      name: 'delete_note',
      description: 'Deletes a saved note by its number.',
      input_schema: {
        type: 'object',
        properties: { id: { type: 'integer', description: 'The note number, without #.' } },
        required: ['id'],
        additionalProperties: false,
      },
      run(input) {
        if (!notes.delete(person, Number(input.id))) throw new Error(`There is no note #${String(input.id)}`);
        return `Deleted #${String(input.id)}.`;
      },
    },
    {
      name: 'set_reminder',
      description: `Texts the owner a reminder in this conversation at a time in ${timezone}.`,
      input_schema: {
        type: 'object',
        properties: {
          at: { type: 'string', description: `When, in ${timezone}, as "YYYY-MM-DD HH:MM".` },
          text: { type: 'string', description: 'What to remind them of, briefly.' },
        },
        required: ['at', 'text'],
        additionalProperties: false,
      },
      async run(input) {
        const at = parseTime(String(input.at), timezone);
        if (at === undefined) throw new Error(`"${String(input.at)}" is not a time like "2026-10-06 09:30"`);
        if (at <= Date.now()) throw new Error(`${formatTime(at, timezone)} has already passed`);
        const text = String(input.text).trim();
        if (!text || text.length > MAX_REMINDER_LENGTH) {
          throw new Error(`The reminder needs 1 to ${MAX_REMINDER_LENGTH} characters of text`);
        }
        await agent.schedule({ thread: ctx.thread, to: ctx.sender.id, text: `Reminder: ${text}`, at: new Date(at) });
        return `Set for ${formatTime(at, timezone)}.`;
      },
    },
    {
      name: 'list_reminders',
      description: 'Lists the reminders still to come, soonest first, with their ids.',
      input_schema: { type: 'object', properties: {}, additionalProperties: false },
      async run() {
        const reminders = await pending();
        if (reminders.length === 0) return 'No reminders set.';
        return reminders
          .map(
            (r) => `${r.id}: ${formatTime(r.at.getTime(), timezone)}, "${'text' in r.request ? r.request.text : ''}"`,
          )
          .join('\n');
      },
    },
    {
      name: 'cancel_reminder',
      description: 'Cancels a reminder by the id list_reminders shows.',
      input_schema: {
        type: 'object',
        properties: { id: { type: 'string' } },
        required: ['id'],
        additionalProperties: false,
      },
      async run(input) {
        // Only this conversation's reminders: an id from anywhere else matches nothing here.
        const reminder = (await pending()).find((r) => r.id === String(input.id));
        if (!reminder || !(await agent.cancelScheduled({ id: reminder.id }))) {
          throw new Error(`There is no reminder ${String(input.id)} still to come`);
        }
        return `Cancelled the reminder for ${formatTime(reminder.at.getTime(), timezone)}.`;
      },
    },
  ];
}
