// Generated by textagent. Yours to edit: opening hours, slots, bookings and reminders.
import { randomUUID } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import type { Agent, MessageContext } from '@textagent/core';
import type { Tool } from './claude.ts';
import { WEEKDAYS, formatTime, isTimezone, isoDate, parseDate, parseTime, toUtc, wallClock } from './time.ts';

/** How long before a booking its reminder is sent. Bookings made later than that get none. */
export const REMINDER_MS = 24 * 60 * 60 * 1000;

type Weekday = (typeof WEEKDAYS)[number];

/** booking.config.json. */
export interface BookingConfig {
  /** IANA timezone the opening hours are in, e.g. "Europe/London". */
  timezone: string;
  slotMinutes: number;
  /** How far ahead people can book. */
  daysAhead: number;
  /** The earliest slot offered is at least this far from now. */
  minNoticeMinutes: number;
  /** Upcoming bookings one person may hold at once. */
  maxBookingsPerPerson: number;
  /** Opening hours per weekday as "HH:MM-HH:MM" ranges; a missing day is closed. */
  hours: Partial<Record<Weekday, string[]>>;
}

export interface Booking {
  id: string;
  /** Epoch ms. */
  start: number;
  end: number;
}

/** Parses and checks booking.config.json, so a typo fails at startup instead of mid-conversation. */
export function loadBookingConfig(json: string): BookingConfig {
  const raw: unknown = JSON.parse(json);
  if (typeof raw !== 'object' || raw === null || Array.isArray(raw)) throw new Error('booking config: not an object');
  const config = raw as Record<string, unknown>; // narrowed field by field below
  const known = ['timezone', 'slotMinutes', 'daysAhead', 'minNoticeMinutes', 'maxBookingsPerPerson', 'hours'];
  const unknown = Object.keys(config).filter((k) => !known.includes(k));
  if (unknown.length) throw new Error(`booking config: unknown setting ${unknown.join(', ')}`);

  const timezone = config.timezone;
  if (typeof timezone !== 'string') throw new Error('booking config: timezone must be a string like "Europe/London"');
  if (!isTimezone(timezone)) throw new Error(`booking config: unknown timezone "${timezone}"`);
  const int = (name: string, min: number, max: number): number => {
    const value = config[name];
    if (!Number.isInteger(value) || (value as number) < min || (value as number) > max) {
      throw new Error(`booking config: ${name} must be a whole number from ${min} to ${max}`);
    }
    return value as number;
  };

  const hours = config.hours;
  if (typeof hours !== 'object' || hours === null || Array.isArray(hours)) {
    throw new Error('booking config: hours must map weekdays (mon, tue, …) to ranges like ["09:00-17:00"]');
  }
  for (const [day, ranges] of Object.entries(hours)) {
    if (!(WEEKDAYS as readonly string[]).includes(day)) throw new Error(`booking config: "${day}" is not mon…sun`);
    if (!Array.isArray(ranges)) throw new Error(`booking config: hours.${day} must be a list of ranges`);
    for (const range of ranges) {
      const parsed = typeof range === 'string' ? parseRange(range) : undefined;
      if (!parsed) throw new Error(`booking config: hours.${day} has "${range}"; use "HH:MM-HH:MM", start before end`);
    }
  }

  return {
    timezone,
    slotMinutes: int('slotMinutes', 5, 24 * 60),
    // agent.schedule() takes dates up to a year ahead; reminders are scheduled at booking time.
    daysAhead: int('daysAhead', 1, 360),
    minNoticeMinutes: int('minNoticeMinutes', 0, 30 * 24 * 60),
    maxBookingsPerPerson: int('maxBookingsPerPerson', 1, 100),
    hours: hours as BookingConfig['hours'], // every key and range checked above
  };
}

/**
 * Bookings in SQLite. A slot's start is UNIQUE, so two people can never hold the same slot,
 * whatever the model does or however two conversations interleave.
 */
export class Bookings {
  readonly config: BookingConfig;
  readonly #db: DatabaseSync;

  constructor(config: BookingConfig, path = 'booking.sqlite') {
    this.config = config;
    this.#db = new DatabaseSync(path);
    this.#db.exec(`CREATE TABLE IF NOT EXISTS bookings (
      id TEXT PRIMARY KEY,
      start INTEGER NOT NULL UNIQUE,
      "end" INTEGER NOT NULL,
      person TEXT NOT NULL,
      created_at INTEGER NOT NULL
    )`);
  }

  /** Free slots from a local date ("YYYY-MM-DD", default today) to the end of the booking window. */
  openSlots(from?: string, now = Date.now(), limit = 30): number[] {
    const { timezone, daysAhead, minNoticeMinutes } = this.config;
    const today = wallClock(now, timezone);
    const first = from === undefined ? Date.UTC(today.year, today.month - 1, today.day) : parseDate(from);
    if (first === undefined) throw new Error(`"${from}" is not a date like 2026-10-06`);
    const lastDay = Date.UTC(today.year, today.month - 1, today.day + daysAhead);
    const earliest = now + minNoticeMinutes * 60_000;
    const taken = this.#db.prepare('SELECT start, "end" FROM bookings WHERE "end" > ?').all(now) as Array<{
      start: number;
      end: number;
    }>; // the row shape of the table above
    const slotMs = this.config.slotMinutes * 60_000;

    const open: number[] = [];
    for (
      let day = Math.max(first, Date.UTC(today.year, today.month - 1, today.day));
      day <= lastDay;
      day += 86_400_000
    ) {
      for (const start of this.#slotsOn(day)) {
        // Overlap, not just equal starts: bookings made under an earlier slot length still block their time.
        if (start < earliest || taken.some((b) => start < b.end && b.start < start + slotMs)) continue;
        open.push(start);
        if (open.length === limit) return open;
      }
    }
    return open;
  }

  /** Throws a message for the model when the slot isn't bookable; it reads it and tells the person. */
  book(person: string, start: number, now = Date.now()): Booking {
    const { maxBookingsPerPerson, slotMinutes } = this.config;
    const day = wallClock(start, this.config.timezone);
    const open = this.openSlots(isoDate(Date.UTC(day.year, day.month - 1, day.day)), now, Infinity);
    if (!open.includes(start)) throw new Error(`${formatTime(start, this.config.timezone)} is not an open slot`);
    if (this.upcoming(person, now).length >= maxBookingsPerPerson) {
      throw new Error(
        `They already have ${maxBookingsPerPerson} upcoming booking(s), the most allowed; cancel one first`,
      );
    }
    const booking = { id: randomUUID(), start, end: start + slotMinutes * 60_000 };
    try {
      this.#db
        .prepare('INSERT INTO bookings (id, start, "end", person, created_at) VALUES (?, ?, ?, ?, ?)')
        .run(booking.id, booking.start, booking.end, person, now);
    } catch (error) {
      if ((error as { errcode?: number }).errcode === 2067) {
        throw new Error(`${formatTime(start, this.config.timezone)} was just taken`); // SQLITE_CONSTRAINT_UNIQUE
      }
      throw error;
    }
    return booking;
  }

  /** This person's bookings that haven't started yet, soonest first. */
  upcoming(person: string, now = Date.now()): Booking[] {
    return this.#db
      .prepare('SELECT id, start, "end" FROM bookings WHERE person = ? AND start > ? ORDER BY start')
      .all(person, now) as unknown as Booking[]; // the row shape of the table above
  }

  /** Cancels one of this person's upcoming bookings; undefined if they have none at that time. */
  cancel(person: string, start: number, now = Date.now()): Booking | undefined {
    return this.#db
      .prepare('DELETE FROM bookings WHERE person = ? AND start = ? AND start > ? RETURNING id, start, "end"')
      .get(person, start, now) as Booking | undefined; // the row shape of the table above
  }

  close(): void {
    this.#db.close();
  }

  /** Slot starts (epoch ms) on one local calendar day, given as UTC midnight of that date. */
  #slotsOn(day: number): number[] {
    const date = new Date(day);
    const ranges = this.config.hours[WEEKDAYS[date.getUTCDay()]!] ?? [];
    const slots: number[] = [];
    for (const range of ranges) {
      const [open, close] = parseRange(range)!; // checked by loadBookingConfig
      for (let minute = open; minute + this.config.slotMinutes <= close; minute += this.config.slotMinutes) {
        const start = toUtc(
          date.getUTCFullYear(),
          date.getUTCMonth() + 1,
          date.getUTCDate(),
          minute,
          this.config.timezone,
        );
        if (start !== undefined) slots.push(start);
      }
    }
    return slots;
  }
}

/** Who a booking belongs to: the sender, on this channel. */
export function personOf(ctx: Pick<MessageContext, 'channel' | 'sender'>): string {
  return `${ctx.channel.name}:${ctx.sender.id}`;
}

/**
 * The booking tools for one conversation. Every tool acts for the person texting, fixed here from the message:
 * nothing Claude or they write can read, book or cancel someone else's slot, or send a reminder elsewhere.
 */
export function bookingTools(
  agent: Pick<Agent, 'schedule' | 'cancelScheduled'>,
  ctx: MessageContext,
  bookings: Bookings,
): Tool[] {
  const { config } = bookings;
  const person = personOf(ctx);
  const slotInput = {
    type: 'object' as const,
    properties: {
      start: { type: 'string', description: 'The slot exactly as listed, e.g. "Tue 2026-10-06 09:30".' },
    },
    required: ['start'],
    additionalProperties: false,
  };
  const slot = (input: Record<string, unknown>): number => {
    const start = parseTime(String(input.start), config.timezone);
    if (start === undefined) throw new Error(`"${String(input.start)}" is not a time like "Tue 2026-10-06 09:30"`);
    return start;
  };

  return [
    {
      name: 'list_open_slots',
      description: `Lists free ${config.slotMinutes}-minute slots, soonest first, from a date to ${config.daysAhead} days from today. Times are ${config.timezone}.`,
      input_schema: {
        type: 'object',
        properties: { from: { type: 'string', description: 'First day to look at, as YYYY-MM-DD.' } },
        required: ['from'],
        additionalProperties: false,
      },
      run(input) {
        const open = bookings.openSlots(String(input.from));
        if (open.length === 0)
          return `No open slots from ${String(input.from)} within the next ${config.daysAhead} days.`;
        return open.map((t) => formatTime(t, config.timezone)).join('\n');
      },
    },
    {
      name: 'book_slot',
      description: 'Books an open slot for the person you are talking to. Only book a time they have clearly chosen.',
      input_schema: slotInput,
      async run(input) {
        const booking = bookings.book(person, slot(input));
        const when = formatTime(booking.start, config.timezone);
        const remindAt = booking.start - REMINDER_MS;
        if (remindAt > Date.now() + 60_000) {
          try {
            await agent.schedule({
              thread: ctx.thread,
              to: ctx.sender.id,
              text: `Reminder: you're booked for ${when} (${config.timezone}). Reply here if you need to cancel.`,
              at: new Date(remindAt),
              key: reminderKey(booking),
            });
          } catch (error) {
            bookings.cancel(person, booking.start); // no booking without its reminder
            throw error;
          }
        }
        return `Booked ${when}.`;
      },
    },
    {
      name: 'list_my_bookings',
      description: "Lists the upcoming bookings of the person you are talking to. You can't see anyone else's.",
      input_schema: { type: 'object', properties: {}, additionalProperties: false },
      run() {
        const mine = bookings.upcoming(person);
        return mine.length ? mine.map((b) => formatTime(b.start, config.timezone)).join('\n') : 'No upcoming bookings.';
      },
    },
    {
      name: 'cancel_booking',
      description: 'Cancels one of the upcoming bookings of the person you are talking to.',
      input_schema: slotInput,
      async run(input) {
        const start = slot(input);
        const booking = bookings.upcoming(person).find((b) => b.start === start);
        if (!booking) throw new Error(`They have no upcoming booking at ${formatTime(start, config.timezone)}`);
        // The reminder goes first: a reminder for a cancelled booking is worse than a booking without one.
        await agent.cancelScheduled({ key: reminderKey(booking) });
        bookings.cancel(person, start);
        return `Cancelled ${formatTime(start, config.timezone)}.`;
      },
    },
  ];
}

function reminderKey(booking: Booking): string {
  return `booking:${booking.id}:reminder`;
}

/** "09:00-17:00" → [540, 1020] minutes after midnight. */
function parseRange(range: string): [number, number] | undefined {
  const m = /^(\d{2}):(\d{2})-(\d{2}):(\d{2})$/.exec(range);
  if (!m) return undefined;
  const [h1, m1, h2, m2] = m.slice(1).map(Number) as [number, number, number, number];
  const open = h1 * 60 + m1;
  const close = h2 * 60 + m2;
  return h1 < 24 && m1 < 60 && h2 <= 24 && m2 < 60 && close <= 24 * 60 && open < close ? [open, close] : undefined;
}
