// Generated by textagent. Yours to edit: this is the loop between a conversation and Claude.
import Anthropic from '@anthropic-ai/sdk';
import type { MessageContext } from '@textagent/core';

export const MODEL = 'claude-opus-5-5';

/** A tool Claude may call. Inputs match `input_schema` exactly (strict mode); return text for Claude to read. */
export interface Tool {
  name: string;
  description: string;
  input_schema: Anthropic.Beta.BetaTool.InputSchema;
  run(input: Record<string, unknown>): Promise<string> | string;
}

export interface ReplyOptions {
  /** Fixed instructions. Message text and sender names are user input: they go in messages, never here. */
  system: string;
  tools?: Tool[];
  /** Earlier messages to include. Default: 20. */
  history?: number;
  /** Model calls per turn before giving up. Default: 8. */
  maxSteps?: number;
}

/** The parts of the Anthropic client this file uses, so tests can pass a fake. */
export type ClaudeClient = { beta: { messages: Pick<Anthropic['beta']['messages'], 'create'> } };

/**
 * One turn: conversation → Claude → tools → Claude … → the text to send (undefined if there is nothing to say).
 * Every model call and tool call is a span in the turn's trace, with token usage, so time and cost show up in
 * the dashboard. Tool inputs and results stay out of span attributes: they may hold what people wrote.
 */
export async function reply(
  client: ClaudeClient,
  ctx: MessageContext,
  options: ReplyOptions,
): Promise<string | undefined> {
  const tools = options.tools ?? [];
  const messages = await historyMessages(ctx, options.history ?? 20);

  for (let step = 1; step <= (options.maxSteps ?? 8); step++) {
    const response = await ctx.trace.span('claude', { step }, async (span) => {
      const r = await client.beta.messages.create({
        model: MODEL,
        max_tokens: 16000,
        // The instructions don't change between turns: cached, they cost a tenth on every later call.
        system: [{ type: 'text', text: options.system, cache_control: { type: 'ephemeral' } }],
        // Texting wants quick answers; raise to 'medium' or 'high' for harder work.
        output_config: { effort: 'low' },
        // If a request is declined, the API retries it on a fallback model within the same call.
        betas: ['server-side-fallback-2026-07-01'],
        fallbacks: 'default',
        ...(tools.length > 0 && {
          tools: tools.map(({ name, description, input_schema }) => ({
            name,
            description,
            input_schema,
            strict: true,
          })),
        }),
        messages,
      });
      span.usage({
        model: r.model,
        inputTokens: r.usage.input_tokens,
        outputTokens: r.usage.output_tokens,
        cacheReadTokens: r.usage.cache_read_input_tokens ?? 0,
        cacheWriteTokens: r.usage.cache_creation_input_tokens ?? 0,
      });
      span.setAttributes({ stopReason: r.stop_reason ?? 'unknown' });
      return r;
    });

    if (response.stop_reason === 'refusal') return "Sorry, I can't help with that.";
    // Appended exactly as returned (thinking blocks included): the API rejects edited history.
    messages.push({ role: 'assistant', content: response.content });
    const calls = response.content.filter((b): b is Anthropic.Beta.BetaToolUseBlock => b.type === 'tool_use');
    if (response.stop_reason !== 'tool_use' || calls.length === 0) return textOf(response.content);

    // All results go back in one message; a failed tool is reported to Claude, not dropped.
    const results = await Promise.all(calls.map((call) => runTool(ctx, tools, call)));
    messages.push({ role: 'user', content: results });
  }
  return 'Sorry, that took me too long to work out. Could you ask again more simply?';
}

async function runTool(
  ctx: MessageContext,
  tools: Tool[],
  call: Anthropic.Beta.BetaToolUseBlock,
): Promise<Anthropic.Beta.BetaToolResultBlockParam> {
  const tool = tools.find((t) => t.name === call.name);
  return ctx.trace.span(`tool:${call.name}`, {}, async (span) => {
    try {
      if (!tool) throw new Error(`There is no tool named ${call.name}`);
      // Strict mode makes the input match the schema; it is an object of the declared fields.
      const content = await tool.run(call.input as Record<string, unknown>);
      return { type: 'tool_result', tool_use_id: call.id, content };
    } catch (error) {
      span.setAttributes({ failed: true });
      return {
        type: 'tool_result',
        tool_use_id: call.id,
        content: error instanceof Error ? error.message : String(error),
        is_error: true,
      };
    }
  });
}

async function historyMessages(ctx: MessageContext, limit: number): Promise<Anthropic.Beta.BetaMessageParam[]> {
  const messages: Anthropic.Beta.BetaMessageParam[] = (await ctx.history(limit)).map((entry) => ({
    role: entry.role === 'agent' ? 'assistant' : 'user',
    content: entry.text || '(sent an attachment)',
  }));
  while (messages[0]?.role === 'assistant') messages.shift(); // a conversation must start with the user
  return messages;
}

function textOf(content: Anthropic.Beta.BetaContentBlock[]): string | undefined {
  const text = content
    .flatMap((block) => (block.type === 'text' ? [block.text] : []))
    .join('\n')
    .trim();
  return text || undefined;
}
