// Generated by textagent. Yours to edit: handing a conversation over to a person on your team.
import { DatabaseSync } from 'node:sqlite';
import type { Agent, MessageContext } from '@textagent/core';
import type { Tool } from './claude.ts';

/** How long the bot stays quiet in a conversation after handing it over. */
export const PAUSE_MS = 24 * 60 * 60 * 1000;

/**
 * Conversations a person has taken over. Kept in SQLite, so a restart doesn't make the bot start talking
 * over the person who is handling it.
 */
export class Handoffs {
  readonly #db: DatabaseSync;

  constructor(path = 'support.sqlite') {
    this.#db = new DatabaseSync(path);
    this.#db.exec('CREATE TABLE IF NOT EXISTS handoffs (conversation TEXT PRIMARY KEY, until INTEGER NOT NULL)');
  }

  pause(conversation: string, now = Date.now()): void {
    this.#db
      .prepare(
        'INSERT INTO handoffs (conversation, until) VALUES (?, ?) ON CONFLICT (conversation) DO UPDATE SET until = excluded.until',
      )
      .run(conversation, now + PAUSE_MS);
  }

  isPaused(conversation: string, now = Date.now()): boolean {
    const row = this.#db.prepare('SELECT until FROM handoffs WHERE conversation = ?').get(conversation) as
      | { until: number }
      | undefined; // the row shape of the table above
    return row !== undefined && row.until > now;
  }

  /** Let the bot answer again before the pause ends. */
  resume(conversation: string): void {
    this.#db.prepare('DELETE FROM handoffs WHERE conversation = ?').run(conversation);
  }

  close(): void {
    this.#db.close();
  }
}

export function conversationOf(ctx: Pick<MessageContext, 'channel' | 'thread'>): string {
  return `${ctx.channel.name}:${ctx.thread.id}`;
}

/** Where handoffs go: a channel and address of yours, from .env. */
export interface Operator {
  channel: string;
  to: string;
}

/**
 * The handoff tool for one conversation. Who receives the summary is fixed here, from .env: nothing Claude
 * or the person texting can change it. The summary itself is written by Claude from what they said.
 */
export function handoffTool(
  agent: Pick<Agent, 'send'>,
  ctx: MessageContext,
  operator: Operator,
  handoffs: Handoffs,
): Tool {
  return {
    name: 'handoff_to_human',
    description:
      "Hand this conversation to a person on the team. Use it when the knowledge base doesn't answer the question, " +
      'when the person asks for a human, or when something needs a person to act (refunds, account changes, complaints). ' +
      'A team member gets your summary and replies to them directly; you stop replying in this conversation for 24 hours.',
    input_schema: {
      type: 'object',
      properties: {
        summary: {
          type: 'string',
          description: 'What the person needs, in one or two sentences, for the team member taking over.',
        },
      },
      required: ['summary'],
      additionalProperties: false,
    },
    async run(input) {
      const who = ctx.sender.name ? `${ctx.sender.name} (${ctx.sender.id})` : ctx.sender.id;
      await agent.send({
        channel: operator.channel,
        to: operator.to,
        text: `Handoff from ${ctx.channel.name} ${who}:\n${String(input.summary)}`,
      });
      handoffs.pause(conversationOf(ctx));
      return 'Done: a team member has your summary and will reply to them directly. Tell them so, in one short message.';
    },
  };
}
