// Generated by textagent. Yours to edit: dates and times in a timezone, with Node's built-in Intl.

export const WEEKDAYS = ['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat'] as const;

export function isTimezone(timezone: string): boolean {
  try {
    new Intl.DateTimeFormat('en-US', { timeZone: timezone });
    return true;
  } catch {
    return false;
  }
}

/** For the system prompt: the model needs today's date to read "next Tuesday" or "tomorrow at 9". */
export function describeNow(timezone: string, now = Date.now()): string {
  return `It is now ${formatTime(now, timezone)} (${timezone}).`;
}

/** "Tue 2026-10-06 09:30", as a clock in `timezone` shows it. */
export function formatTime(t: number, timezone: string): string {
  const w = wallClock(t, timezone);
  const weekday = WEEKDAYS[new Date(Date.UTC(w.year, w.month - 1, w.day)).getUTCDay()]!;
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${weekday[0]!.toUpperCase()}${weekday.slice(1)} ${w.year}-${pad(w.month)}-${pad(w.day)} ${pad(w.hour)}:${pad(w.minute)}`;
}

/** The reverse of formatTime; the weekday is optional and not trusted. Undefined for times that don't exist. */
export function parseTime(text: string, timezone: string): number | undefined {
  const m = /^(?:[A-Za-z]{3} )?(\d{4})-(\d{2})-(\d{2}) (\d{2}):(\d{2})$/.exec(text.trim());
  if (!m) return undefined;
  const [year, month, day, hour, minute] = m.slice(1).map(Number) as [number, number, number, number, number];
  if (hour > 23 || minute > 59 || parseDate(`${m[1]}-${m[2]}-${m[3]}`) === undefined) return undefined;
  return toUtc(year, month, day, hour * 60 + minute, timezone);
}

/** "2026-10-06" → UTC midnight of that date, or undefined for anything that isn't a real date. */
export function parseDate(text: string): number | undefined {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(text.trim());
  if (!m) return undefined;
  const t = Date.UTC(Number(m[1]), Number(m[2]) - 1, Number(m[3]));
  return isoDate(t) === text.trim() ? t : undefined; // rejects 2026-02-30
}

export function isoDate(t: number): string {
  return new Date(t).toISOString().slice(0, 10);
}

export interface Wall {
  year: number;
  month: number;
  day: number;
  hour: number;
  minute: number;
}

const formatters = new Map<string, Intl.DateTimeFormat>();

/** The date and time a clock in `timezone` shows at epoch ms `t`. */
export function wallClock(t: number, timezone: string): Wall {
  let format = formatters.get(timezone);
  if (!format) {
    format = new Intl.DateTimeFormat('en-US', {
      timeZone: timezone,
      hourCycle: 'h23',
      year: 'numeric',
      month: 'numeric',
      day: 'numeric',
      hour: 'numeric',
      minute: 'numeric',
    });
    formatters.set(timezone, format);
  }
  const parts = Object.fromEntries(format.formatToParts(t).map((p) => [p.type, Number(p.value)]));
  return { year: parts.year!, month: parts.month!, day: parts.day!, hour: parts.hour!, minute: parts.minute! };
}

/**
 * Epoch ms of a local date and time in `timezone`; undefined when the clocks skip that time (DST starts).
 * Guess with the offset at the naive UTC time, then correct once with the offset at the guess.
 */
export function toUtc(year: number, month: number, day: number, minutes: number, timezone: string): number | undefined {
  const naive = Date.UTC(year, month - 1, day, 0, minutes);
  const offsetAt = (t: number) => {
    const w = wallClock(t, timezone);
    return Date.UTC(w.year, w.month - 1, w.day, w.hour, w.minute) - Math.floor(t / 60_000) * 60_000;
  };
  let t = naive - offsetAt(naive);
  t = naive - offsetAt(t);
  const w = wallClock(t, timezone);
  return Date.UTC(w.year, w.month - 1, w.day, w.hour, w.minute) === naive ? t : undefined;
}
